# Generated by Django 5.1.3 on 2024-11-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.TimeField(verbose_name='Продолжительность'),
        ),
    ]
