# Generated by Django 5.1.3 on 2024-12-04 14:27

import media.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractmedia',
            name='release_date',
            field=models.DateField(validators=[media.validators.release_date_validator], verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='historicalmovie',
            name='release_date',
            field=models.DateField(validators=[media.validators.release_date_validator], verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='historicaltvshow',
            name='release_date',
            field=models.DateField(validators=[media.validators.release_date_validator], verbose_name='Дата выхода'),
        ),
    ]
