# Generated by Django 5.1.3 on 2024-12-08 17:39

import media.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_abstractmedia_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractmedia',
            name='title',
            field=models.CharField(max_length=100, validators=[media.validators.validate_title], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[media.validators.validate_title], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[media.validators.validate_title], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalmovie',
            name='title',
            field=models.CharField(max_length=100, validators=[media.validators.validate_title], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicaltvshow',
            name='title',
            field=models.CharField(max_length=100, validators=[media.validators.validate_title], verbose_name='Название'),
        ),
    ]
