# Generated by Django 5.1.4 on 2025-01-06 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_abstractmedia_title_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('tvshow', 'TV Show')], max_length=10)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='media_posters/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='media.country')),
                ('genre', models.ManyToManyField(related_name='media', to='media.genre')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
