# Generated by Django 5.1.4 on 2025-01-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_country_options_alter_genre_options_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='genre',
            new_name='genres',
        ),
    ]
