# Generated by Django 5.1.4 on 2025-01-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_rename_genre_media_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
