# Generated by Django 5.1.4 on 2025-01-06 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_remove_media_genres_alter_media_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.genre')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='genres',
            field=models.ManyToManyField(through='media.MediaGenre', to='media.genre'),
        ),
    ]
