# Generated by Django 5.1.4 on 2025-01-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_mediagenre_media_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media_files/'),
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
