# Generated by Django 5.1.4 on 2025-01-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_media_file_media_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-release_date'], 'verbose_name': 'Другое медиа', 'verbose_name_plural': 'Другие медиа'},
        ),
        migrations.AddField(
            model_name='abstractmedia',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='historicalmovie',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='historicaltvshow',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
